# Generated by Django 5.2.6 on 2025-09-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Security deposit amount', max_digits=10),
        ),
    ]
