# Generated by Django 5.2.6 on 2025-09-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_security_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available_from',
            field=models.DateField(blank=True, help_text='Date from when the room is available', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='food_included',
            field=models.BooleanField(default=False),
        ),
    ]
