# Generated by Django 5.2.6 on 2025-09-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_available_from_room_food_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.CharField(blank=True, help_text='Floor number (e.g., Ground, 1st, 2nd)', max_length=20, null=True),
        ),
    ]
