# Generated by Django 5.2.6 on 2025-09-26 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_floor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('fake', 'Fake Listing'), ('spam', 'Spam'), ('misleading', 'Misleading Information'), ('scam', 'Potential Scam'), ('duplicate', 'Duplicate Listing'), ('inappropriate_images', 'Inappropriate Images'), ('wrong_location', 'Wrong Location'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='Please provide details about the issue')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=15)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='rooms.room')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('room', 'reporter')},
            },
        ),
    ]
